version: '3'

services:
  database:
    image: postgres:16-alpine
    container_name: db_postgres
    hostname: database_host
    environment:
      -  POSTGRES_PASSWORD = 123
      -  POSTGRES_DB  = postgres
    expose:
      - "5432"
    volumes:
      - /var/docker-db-lab/:/var/lib/postgresql/data

    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "127.0.0.1:80:80"
    networks:
      - app-network
    depends_on:
      - database
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
